# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-62183976-3
favicon: /favicon.png
twitter:
google_plus: 113838943770679866520
fb_admins:
fb_app_id: